[package]
name = "msms_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "^4.5.2"
serde_json = "^1.0.107"
serde = {version = "^1.0.188", features = ["derive"]}
binary-ensemble = "^0.1.1"